window.PROJECTS = [
  {
    id: "iris-flower-classification",
    title: "Iris Flower Classification",
    question: "Can flower species be predicted from physical measurements?",
    description: "Built and evaluated Decision Tree and Logistic Regression classifiers using sepal and petal measurements from the Iris dataset.",
    finding: "Both models achieved 100% accuracy on the project test split, with petal measurements showing the clearest visual separation.",
    category: "Machine Learning",
    tags: ["Python", "pandas", "scikit-learn", "Classification", "Matplotlib"],
    status: "Completed",
    date: "2026-07",
    github: "https://github.com/brookeojemen/iris-flower-classifications",
    caseStudy: "project-details/iris.html",
    image: "project-images/iris-flower-classification.png",
    imageAlt: "Scatter plot comparing Iris flower measurements by species",
    metrics: ["150 flowers", "3 species", "2 models"]
  },
  {
    id: "penguin-data-analysis",
    title: "Penguin Data Analysis",
    question: "How do physical measurements differ among Palmer penguin species?",
    description: "Cleaned and explored the Palmer Penguins dataset using descriptive statistics and visual comparisons of culmen length, flipper length, body mass, and island.",
    finding: "Gentoo penguins had the highest average flipper length and body mass, while Chinstrap penguins had greater average culmen length than Adelie penguins.",
    category: "Data Analysis",
    tags: ["Python", "pandas", "Matplotlib", "EDA", "Data Cleaning"],
    status: "Completed",
    date: "2026-07",
    github: "https://github.com/brookeojemen/Penguin-Data-Analysis",
    caseStudy: "project-details/penguins.html",
    image: "project-images/penguin-data-analysis.png",
    imageAlt: "Scatter plots comparing Adelie, Chinstrap, and Gentoo penguin measurements",
    metrics: ["344 observations", "3 species", "3 visual analyses"]
  },
  {
    id: "customer-behavior-analysis",
    title: "Customer Behavior Analysis & RFM Segmentation",
    question: "Can purchasing behavior identify meaningful customer groups?",
    description: "Analyzed online retail transactions, engineered Recency, Frequency, and Monetary features, and applied K-Means clustering to segment customers.",
    finding: "The final four-cluster solution produced interpretable groups ranging from low-activity customers to high-value loyal customers.",
    category: "Machine Learning",
    tags: ["Python", "pandas", "scikit-learn", "RFM", "K-Means"],
    status: "Completed",
    date: "2026-07",
    github: "https://github.com/brookeojemen/customer-behavior-analysis",
    caseStudy: "project-details/customer-behavior.html",
    image: "project-images/customer-behavior-analysis.png",
    imageAlt: "Scatter plot of customer order frequency and total spending colored by four K-Means clusters",
    metrics: ["396,769 transactions", "RFM features", "4 segments"]
  },
  {
    id: "housing-price-prediction",
    title: "Housing Price Prediction",
    question: "Which property features are most useful for predicting sale price?",
    description: "Regression project in progress using the Ames housing training data. The current work includes initial dataset inspection and preparation for cleaning, exploration, feature processing, and model evaluation.",
    finding: "In progress: results and model metrics will be added after the regression workflow is completed.",
    category: "Machine Learning",
    tags: ["Python", "pandas", "Regression", "Feature Engineering"],
    status: "In Progress",
    date: "2026-07",
    github: "https://github.com/brookeojemen/HousingPrediction",
    caseStudy: "project-details/housing.html",
    image: "",
    imageAlt: "Housing Price Prediction regression project currently in progress",
    metrics: ["1,460 rows", "81 columns", "Regression"]
  }  ,{
    id: "backend-project-coming-soon",
    title: "Backend Project — Coming Soon",
    question: "How can a well-structured backend API support a practical application?",
    description: "Planned Java backend project focused on applying Spring Boot, Maven, REST API design, and database concepts in a complete application.",
    finding: "Planned: implementation details and technical results will be added as development begins.",
    category: "Backend",
    tags: ["Java", "Spring Boot", "Maven", "REST API", "Planned"],
    status: "Planned",
    date: "2026-08",
    github: "",
    caseStudy: "",
    image: "",
    imageAlt: "Planned Java backend development project",
    metrics: ["Java", "Spring Boot", "REST API"]
  }
];
